version: "3.4"

services:
  xinfin-testnet-node:
    build: ./
    image: xinfinorg/xinfin-testnet-node:1130199b95301c8696e1fc94eccb7e0549c8b262
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
      - "./start-node.sh:/work/start-node.sh"
      - "./bootnodes.list:/work/bootnodes.list"
      - "./.pwd:/work/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    restart: "always"
    env_file: .env
    ports:
      - "30303:30303"
      - "8545:8545"

  netapis:
    build: ./netapis
    image: xinfinorg/netapis
    restart: "on-failure:10"
    volumes:
      - "./netapis/app.json:/netapis/app.json"
      - "/etc/localtime:/etc/localtime:ro"
    env_file: .env
    depends_on:
      - xinfin-testnet-node 
